-- ============================================================================
-- Audit trail
--
-- SOC 2 wants to answer "who changed what, when" without relying on anyone
-- remembering to log it. So the trail is written by triggers, not by app code,
-- and it is append-only: no UPDATE or DELETE policy exists, and the privileges
-- are revoked outright, so nothing reachable through the API can rewrite it.
-- ============================================================================

create table public.audit_log (
  id          bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id    uuid,                       -- null for service-role / system writes
  actor_email text,
  action      text not null check (action in ('insert','update','delete')),
  table_name  text not null,
  record_id   text,
  franchise_id uuid,                      -- denormalised so operators can read their own
  before      jsonb,
  after       jsonb
);

create index audit_log_table_idx     on public.audit_log (table_name, occurred_at desc);
create index audit_log_actor_idx     on public.audit_log (actor_id, occurred_at desc);
create index audit_log_franchise_idx on public.audit_log (franchise_id, occurred_at desc);

alter table public.audit_log enable row level security;

-- Read-only, and scoped. Operators see activity on their own franchise.
create policy audit_read on public.audit_log
  for select to authenticated
  using (
    public.is_staff()
    or franchise_id in (select public.my_franchise_ids())
  );

-- Deliberately no insert/update/delete policy: the trigger is security definer
-- and bypasses RLS, so it can still write. Nothing else can.
-- The blanket `grant select on all tables` in 0002 ran before this table
-- existed, so grant it explicitly or the read policy can never fire.
grant select on public.audit_log to authenticated;
revoke insert, update, delete on public.audit_log from authenticated, anon;
revoke all on public.audit_log from anon;

-- ---------------------------------------------------------------------------
-- Generic trigger. Works out the franchise from whichever shape the row has.
-- ---------------------------------------------------------------------------
create or replace function public.write_audit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_before jsonb;
  v_after  jsonb;
  v_id     text;
  v_fr     uuid;
  v_email  text;
begin
  if tg_op = 'DELETE' then
    v_before := to_jsonb(old);
    v_after  := null;
  elsif tg_op = 'INSERT' then
    v_before := null;
    v_after  := to_jsonb(new);
  else
    v_before := to_jsonb(old);
    v_after  := to_jsonb(new);
    if v_before = v_after then
      return null;   -- touch with no change: nothing worth recording
    end if;
  end if;

  v_id := coalesce(v_after ->> 'id', v_before ->> 'id',
                   v_after ->> 'order_id', v_before ->> 'order_id');

  -- franchise_id directly on the row, else via the parent order
  v_fr := nullif(coalesce(v_after ->> 'franchise_id', v_before ->> 'franchise_id'), '')::uuid;
  if v_fr is null then
    select o.franchise_id into v_fr
    from public.orders o
    where o.id = nullif(coalesce(v_after ->> 'order_id', v_before ->> 'order_id'), '')::uuid;
  end if;

  select s.email into v_email from public.staff s where s.user_id = public.current_user_id();
  if v_email is null then
    select fo.email into v_email
    from public.franchise_operators fo
    where fo.user_id = public.current_user_id()
    limit 1;
  end if;

  insert into public.audit_log
    (actor_id, actor_email, action, table_name, record_id, franchise_id, before, after)
  values
    (public.current_user_id(), v_email, lower(tg_op), tg_table_name, v_id, v_fr, v_before, v_after);

  return null;   -- after trigger
end;
$$;

-- Audit the tables that carry money, access, or a commitment to print.
create trigger audit_orders
  after insert or update or delete on public.orders
  for each row execute function public.write_audit();

create trigger audit_order_zips
  after insert or update or delete on public.order_zips
  for each row execute function public.write_audit();

create trigger audit_order_criteria
  after insert or update or delete on public.order_criteria
  for each row execute function public.write_audit();

create trigger audit_franchise_operators
  after insert or update or delete on public.franchise_operators
  for each row execute function public.write_audit();

create trigger audit_franchise_zips
  after insert or update or delete on public.franchise_zips
  for each row execute function public.write_audit();

create trigger audit_formats
  after insert or update or delete on public.formats
  for each row execute function public.write_audit();

create trigger audit_staff
  after insert or update or delete on public.staff
  for each row execute function public.write_audit();
