-- ============================================================================
-- Authentication event log + magic-link rate limiting
--
-- Two SOC 2 gaps closed here:
--
--   CC7.2  audit_log covers business tables only, so sign-in attempts, session
--          creation and revocation were invisible. They are security events and
--          need to be logged and reviewable.
--
--   CC6.6  the magic-link endpoint was an unauthenticated, unthrottled
--          email-sending relay. Anyone could have used it to spam an address
--          or to probe which addresses are registered.
--
-- The rate limit is derived from this same table rather than from in-memory
-- counters, deliberately: Railway can run more than one instance, and an
-- in-process limiter would then allow N times the intended rate while also
-- resetting on every deploy.
--
-- Append-only, like audit_log: written by a security-definer function, with
-- INSERT/UPDATE/DELETE revoked from every reachable role.
-- ============================================================================

create type public.auth_event_kind as enum (
  'link_requested',     -- someone asked for a magic link
  'link_rate_limited',  -- request refused by the throttle
  'link_send_failed',   -- the email provider rejected it
  'signin_succeeded',   -- link redeemed, session created
  'signout',
  'session_revoked'     -- staff or the operator killed a session
);

create table public.auth_events (
  id          bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  kind        public.auth_event_kind not null,
  email       citext,                 -- as supplied; may not match any account
  user_id     uuid references public.app_users(id) on delete set null,
  ip          inet,
  user_agent  text,
  detail      jsonb
);

create index auth_events_email_idx on public.auth_events (email, occurred_at desc);
create index auth_events_ip_idx    on public.auth_events (ip, occurred_at desc);
create index auth_events_user_idx  on public.auth_events (user_id, occurred_at desc);
create index auth_events_kind_idx  on public.auth_events (kind, occurred_at desc);

alter table public.auth_events enable row level security;

-- Staff only. An operator has no business reading sign-in attempts for an
-- address, theirs or anyone's - that is a security log, not account activity.
create policy auth_events_staff_read on public.auth_events
  for select to authenticated
  using (public.is_staff());

grant select on public.auth_events to authenticated;
revoke insert, update, delete on public.auth_events from authenticated, anon;
revoke all on public.auth_events from anon;

-- ---------------------------------------------------------------------------
-- Writer. security definer so the app can log without being able to rewrite.
-- Callable with no user context: sign-in events happen before a session exists.
-- ---------------------------------------------------------------------------
create or replace function public.log_auth_event(
  p_kind       public.auth_event_kind,
  p_email      text default null,
  p_user_id    uuid  default null,
  p_ip         text  default null,
  p_user_agent text  default null,
  p_detail     jsonb default null
) returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ip inet;
begin
  -- A malformed or proxy-mangled address must never break sign-in.
  begin
    v_ip := nullif(trim(p_ip), '')::inet;
  exception when others then
    v_ip := null;
  end;

  insert into public.auth_events (kind, email, user_id, ip, user_agent, detail)
  values (p_kind, nullif(trim(p_email), ''), p_user_id, v_ip,
          left(coalesce(p_user_agent, ''), 400), p_detail);
end;
$$;

-- ---------------------------------------------------------------------------
-- Throttle. Counts recent requests for this address and from this IP.
--
-- Returns the decision plus the counts so the caller can log why, but the
-- caller must NOT tell the browser which limit was hit - see the uniform
-- response in the sign-in action.
-- ---------------------------------------------------------------------------
create or replace function public.magic_link_allowed(
  p_email text,
  p_ip    text default null,
  p_window interval default interval '15 minutes',
  p_max_per_email integer default 3,
  p_max_per_ip    integer default 12
) returns table (allowed boolean, email_count integer, ip_count integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ip inet;
  v_e  integer;
  v_i  integer := 0;
begin
  begin
    v_ip := nullif(trim(p_ip), '')::inet;
  exception when others then
    v_ip := null;
  end;

  select count(*) into v_e
    from public.auth_events
   where kind = 'link_requested'
     and email = nullif(trim(p_email), '')
     and occurred_at > now() - p_window;

  if v_ip is not null then
    select count(*) into v_i
      from public.auth_events
     where kind = 'link_requested'
       and ip = v_ip
       and occurred_at > now() - p_window;
  end if;

  return query select (v_e < p_max_per_email and v_i < p_max_per_ip), v_e, v_i;
end;
$$;

-- ---------------------------------------------------------------------------
-- Quarterly access review (CC6.2). Run this, keep the output as evidence.
-- ---------------------------------------------------------------------------
create or replace view public.access_review as
select
  f.name                                as franchise,
  f.city || ', ' || f.state             as location,
  au.email,
  au.full_name,
  fo.is_active,
  fo.invited_at,
  fo.accepted_at,
  (select max(occurred_at) from public.auth_events e
    where e.user_id = fo.user_id and e.kind = 'signin_succeeded') as last_signin,
  exists (select 1 from public.staff s
           where s.user_id = fo.user_id and s.is_active)          as is_staff
from public.franchise_operators fo
join public.franchises f  on f.id  = fo.franchise_id
join public.app_users  au on au.id = fo.user_id;

comment on view public.access_review is
  'Who can act for which franchise, with last sign-in. For the quarterly access review; retain the output as audit evidence.';

alter view public.access_review set (security_invoker = true);
grant select on public.access_review to authenticated;

revoke all on function public.log_auth_event(public.auth_event_kind, text, uuid, text, text, jsonb) from public;
revoke all on function public.magic_link_allowed(text, text, interval, integer, integer) from public;
grant execute on function public.log_auth_event(public.auth_event_kind, text, uuid, text, text, jsonb) to authenticated;
grant execute on function public.magic_link_allowed(text, text, interval, integer, integer) to authenticated;
